/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaardebloemRouteImport } from './routes/waardebloem'
import { Route as IndexRouteImport } from './routes/index'

const WaardebloemRoute = WaardebloemRouteImport.update({
  id: '/waardebloem',
  path: '/waardebloem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/waardebloem': typeof WaardebloemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/waardebloem': typeof WaardebloemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/waardebloem': typeof WaardebloemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/waardebloem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/waardebloem'
  id: '__root__' | '/' | '/waardebloem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WaardebloemRoute: typeof WaardebloemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waardebloem': {
      id: '/waardebloem'
      path: '/waardebloem'
      fullPath: '/waardebloem'
      preLoaderRoute: typeof WaardebloemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WaardebloemRoute: WaardebloemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
