/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaardebloemRouteImport } from './routes/waardebloem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaardebloemIndexRouteImport } from './routes/waardebloem.index'
import { Route as WaardebloemDefinitiefRouteImport } from './routes/waardebloem.definitief'
import { Route as WaardebloemConcept1RouteImport } from './routes/waardebloem.concept-1'

const WaardebloemRoute = WaardebloemRouteImport.update({
  id: '/waardebloem',
  path: '/waardebloem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaardebloemIndexRoute = WaardebloemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WaardebloemRoute,
} as any)
const WaardebloemDefinitiefRoute = WaardebloemDefinitiefRouteImport.update({
  id: '/definitief',
  path: '/definitief',
  getParentRoute: () => WaardebloemRoute,
} as any)
const WaardebloemConcept1Route = WaardebloemConcept1RouteImport.update({
  id: '/concept-1',
  path: '/concept-1',
  getParentRoute: () => WaardebloemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/waardebloem': typeof WaardebloemRouteWithChildren
  '/waardebloem/concept-1': typeof WaardebloemConcept1Route
  '/waardebloem/definitief': typeof WaardebloemDefinitiefRoute
  '/waardebloem/': typeof WaardebloemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/waardebloem/concept-1': typeof WaardebloemConcept1Route
  '/waardebloem/definitief': typeof WaardebloemDefinitiefRoute
  '/waardebloem': typeof WaardebloemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/waardebloem': typeof WaardebloemRouteWithChildren
  '/waardebloem/concept-1': typeof WaardebloemConcept1Route
  '/waardebloem/definitief': typeof WaardebloemDefinitiefRoute
  '/waardebloem/': typeof WaardebloemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/waardebloem'
    | '/waardebloem/concept-1'
    | '/waardebloem/definitief'
    | '/waardebloem/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/waardebloem/concept-1'
    | '/waardebloem/definitief'
    | '/waardebloem'
  id:
    | '__root__'
    | '/'
    | '/waardebloem'
    | '/waardebloem/concept-1'
    | '/waardebloem/definitief'
    | '/waardebloem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WaardebloemRoute: typeof WaardebloemRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waardebloem': {
      id: '/waardebloem'
      path: '/waardebloem'
      fullPath: '/waardebloem'
      preLoaderRoute: typeof WaardebloemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waardebloem/': {
      id: '/waardebloem/'
      path: '/'
      fullPath: '/waardebloem/'
      preLoaderRoute: typeof WaardebloemIndexRouteImport
      parentRoute: typeof WaardebloemRoute
    }
    '/waardebloem/definitief': {
      id: '/waardebloem/definitief'
      path: '/definitief'
      fullPath: '/waardebloem/definitief'
      preLoaderRoute: typeof WaardebloemDefinitiefRouteImport
      parentRoute: typeof WaardebloemRoute
    }
    '/waardebloem/concept-1': {
      id: '/waardebloem/concept-1'
      path: '/concept-1'
      fullPath: '/waardebloem/concept-1'
      preLoaderRoute: typeof WaardebloemConcept1RouteImport
      parentRoute: typeof WaardebloemRoute
    }
  }
}

interface WaardebloemRouteChildren {
  WaardebloemConcept1Route: typeof WaardebloemConcept1Route
  WaardebloemDefinitiefRoute: typeof WaardebloemDefinitiefRoute
  WaardebloemIndexRoute: typeof WaardebloemIndexRoute
}

const WaardebloemRouteChildren: WaardebloemRouteChildren = {
  WaardebloemConcept1Route: WaardebloemConcept1Route,
  WaardebloemDefinitiefRoute: WaardebloemDefinitiefRoute,
  WaardebloemIndexRoute: WaardebloemIndexRoute,
}

const WaardebloemRouteWithChildren = WaardebloemRoute._addFileChildren(
  WaardebloemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WaardebloemRoute: WaardebloemRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
